import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import localFont from "next/font/local";

const calSans = localFont({
  src: "../public/fonts/CalSans-Regular.woff2",
  variable: "--font-cal-sans",
});

const nosy = localFont({
  src: "../public/fonts/Nosy.otf",
  variable: "--font-nosy",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="pl" className={`${calSans.variable} ${nosy.variable}`}>
      <body className="antialiased bg-gray-50">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
